apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-pkfb
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zkfo-tenant/rhtap-demo-app/hacbs-test-project-pkfb@sha256:386a4ab6204c4592d56c46566993d27228724cec9e4d2c953806299366a59b9f
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
