apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-pkfb
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zkfo-tenant/rhtap-demo-app/hacbs-test-project-pkfb@sha256:12d0aecc2f7cab6ec90dd8dfeac641c0552a18bf18e220a0c7eb4e5cee3ef02f
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
