apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-pkfb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-pkfb
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-pkfb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-pkfb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-pkfb
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zkfo-tenant/rhtap-demo-app/hacbs-test-project-pkfb@sha256:12d0aecc2f7cab6ec90dd8dfeac641c0552a18bf18e220a0c7eb4e5cee3ef02f
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
